TCore.TauntGUI = TCore.TauntGUI or {}

local TauntGUI = TCore.TauntGUI
local myTaunt = CreateClientConVar("cl_taunt", "f_NeedToPee", true, false)
TauntGUI.Taunts = {}
table.insert(TauntGUI.Taunts,{"Accolades","f_Accolades"})
table.insert(TauntGUI.Taunts,{"Acrobatic Superhero","f_Acrobatic_Superhero"})
table.insert(TauntGUI.Taunts,{"AerobicChamp","f_AerobicChamp"})
table.insert(TauntGUI.Taunts,{"AfroHouse","f_AfroHouse"})
table.insert(TauntGUI.Taunts,{"AirHorn","f_AirHorn"})
table.insert(TauntGUI.Taunts,{"ArmUp","f_ArmUp"})
table.insert(TauntGUI.Taunts,{"ArmWave","f_ArmWave"})
table.insert(TauntGUI.Taunts,{"Ashton_Boardwalk_v2","f_Ashton_Boardwalk_v2"})
table.insert(TauntGUI.Taunts,{"Assassin_Salute","f_Assassin_Salute"})
table.insert(TauntGUI.Taunts,{"Assassin_Vest","f_Assassin_Vest"})
table.insert(TauntGUI.Taunts,{"BalletSpin","f_BalletSpin"})
table.insert(TauntGUI.Taunts,{"Banana","f_Banana"})
table.insert(TauntGUI.Taunts,{"BandOfTheFort","f_BandOfTheFort"})
table.insert(TauntGUI.Taunts,{"Basketball","f_Basketball"})
table.insert(TauntGUI.Taunts,{"Basketball_Tricks","f_Basketball_Tricks"})
table.insert(TauntGUI.Taunts,{"Battle_Horn","f_Battle_Horn"})
table.insert(TauntGUI.Taunts,{"BBD","f_BBD"})
table.insert(TauntGUI.Taunts,{"Bendi","f_Bendi"})
table.insert(TauntGUI.Taunts,{"BlackMonday","f_BlackMonday"})
table.insert(TauntGUI.Taunts,{"BlackMondayFight","f_BlackMondayFight"})
table.insert(TauntGUI.Taunts,{"BlackMonday_Female","f_BlackMonday_Female"})
table.insert(TauntGUI.Taunts,{"BlowingBubbles","f_BlowingBubbles"})
table.insert(TauntGUI.Taunts,{"Blow_Kiss","f_Blow_Kiss"})
table.insert(TauntGUI.Taunts,{"Boogie_Down","f_Boogie_Down"})
table.insert(TauntGUI.Taunts,{"Breakboy","f_Breakboy"})
table.insert(TauntGUI.Taunts,{"Break_Dance","f_Break_Dance"})
table.insert(TauntGUI.Taunts,{"Break_Dance_v2","f_Break_Dance_v2"})
table.insert(TauntGUI.Taunts,{"Bring_It_On","f_Bring_It_On"})
table.insert(TauntGUI.Taunts,{"BunnyHop","f_BunnyHop"})
table.insert(TauntGUI.Taunts,{"BurgerFlipping","f_BurgerFlipping"})
table.insert(TauntGUI.Taunts,{"Burpee","f_Burpee"})
table.insert(TauntGUI.Taunts,{"CactusTpose","f_CactusTpose"})
table.insert(TauntGUI.Taunts,{"Calculated","f_Calculated"})
table.insert(TauntGUI.Taunts,{"Candy_Dance","f_Candy_Dance"})
table.insert(TauntGUI.Taunts,{"Capoeira","f_Capoeira"})
table.insert(TauntGUI.Taunts,{"Cartwheel","f_Cartwheel"})
table.insert(TauntGUI.Taunts,{"Celebration","f_Celebration"})
table.insert(TauntGUI.Taunts,{"Charleston","f_Charleston"})
table.insert(TauntGUI.Taunts,{"Cheerleader","f_Cheerleader"})
table.insert(TauntGUI.Taunts,{"Chicken","f_Chicken"})
table.insert(TauntGUI.Taunts,{"Chicken_Moves","f_Chicken_Moves"})
table.insert(TauntGUI.Taunts,{"Chopstick","f_Chopstick"})
table.insert(TauntGUI.Taunts,{"Chug","f_Chug"})
table.insert(TauntGUI.Taunts,{"ClapperBoard","f_ClapperBoard"})
table.insert(TauntGUI.Taunts,{"Confused","f_Confused"})
table.insert(TauntGUI.Taunts,{"Conga","f_Conga"})
table.insert(TauntGUI.Taunts,{"Cool_Robot","f_Cool_Robot"})
table.insert(TauntGUI.Taunts,{"Cowbell","f_Cowbell"})
table.insert(TauntGUI.Taunts,{"CowboyDance","f_CowboyDance"})
table.insert(TauntGUI.Taunts,{"Crab_Dance","f_Crab_Dance"})
table.insert(TauntGUI.Taunts,{"Crackshot","f_Crackshot"})
table.insert(TauntGUI.Taunts,{"CrazyDance","f_CrazyDance"})
table.insert(TauntGUI.Taunts,{"CrazyFeet","f_CrazyFeet"})
table.insert(TauntGUI.Taunts,{"Cross_Legs","f_Cross_Legs"})
table.insert(TauntGUI.Taunts,{"Cry","f_Cry"})
table.insert(TauntGUI.Taunts,{"DanceMoves","f_DanceMoves"})
table.insert(TauntGUI.Taunts,{"Dance_Disco_T3","f_Dance_Disco_T3"})
table.insert(TauntGUI.Taunts,{"Dance_NoBones","f_Dance_NoBones"})
table.insert(TauntGUI.Taunts,{"Dance_Off","f_Dance_Off"})
table.insert(TauntGUI.Taunts,{"Dance_Shoot","f_Dance_Shoot"})
table.insert(TauntGUI.Taunts,{"Dance_SwipeIt","f_Dance_SwipeIt"})
table.insert(TauntGUI.Taunts,{"Dance_Worm","f_Dance_Worm"})
table.insert(TauntGUI.Taunts,{"Dancing_Girl","f_Dancing_Girl"})
table.insert(TauntGUI.Taunts,{"DarkFireLegends","f_DarkFireLegends"})
table.insert(TauntGUI.Taunts,{"Davinci","f_Davinci"})
table.insert(TauntGUI.Taunts,{"DeepDab","f_DeepDab"})
table.insert(TauntGUI.Taunts,{"DG_Disco","f_DG_Disco"})
table.insert(TauntGUI.Taunts,{"Disagree","f_Disagree"})
table.insert(TauntGUI.Taunts,{"DivinePose","f_DivinePose"})
table.insert(TauntGUI.Taunts,{"DJ_Drop","f_DJ_Drop"})
table.insert(TauntGUI.Taunts,{"Doublesnap","f_Doublesnap"})
table.insert(TauntGUI.Taunts,{"DreamFeet","f_DreamFeet"})
table.insert(TauntGUI.Taunts,{"Drum_Major","f_Drum_Major"})
table.insert(TauntGUI.Taunts,{"Dumbbell_Lift","f_Dumbbell_Lift"})
table.insert(TauntGUI.Taunts,{"Dunk","f_Dunk"})
table.insert(TauntGUI.Taunts,{"Dust_Off_Hands","f_Dust_Off_Hands"})
table.insert(TauntGUI.Taunts,{"Dust_Off_Shoulders","f_Dust_Off_Shoulders"})
table.insert(TauntGUI.Taunts,{"Eastern_Bloc","f_Eastern_Bloc"})
table.insert(TauntGUI.Taunts,{"Eating_Popcorn","f_Eating_Popcorn"})
table.insert(TauntGUI.Taunts,{"ElectroShuffle2","f_ElectroShuffle2"})
table.insert(TauntGUI.Taunts,{"ElectroSwing","f_ElectroSwing"})
table.insert(TauntGUI.Taunts,{"Epic_Sax_Guy","f_Epic_Sax_Guy"})
table.insert(TauntGUI.Taunts,{"Facepalm","f_Facepalm"})
table.insert(TauntGUI.Taunts,{"FancyFeet","f_FancyFeet"})
table.insert(TauntGUI.Taunts,{"FancyWorkout","f_FancyWorkout"})
table.insert(TauntGUI.Taunts,{"Festivus","f_Festivus"})
table.insert(TauntGUI.Taunts,{"FingerGunsV2","f_FingerGunsV2"})
table.insert(TauntGUI.Taunts,{"FireStick","f_FireStick"})
table.insert(TauntGUI.Taunts,{"Fistpump_Celebration","f_Fistpump_Celebration"})
table.insert(TauntGUI.Taunts,{"Flamenco","f_Flamenco"})
table.insert(TauntGUI.Taunts,{"Flex","f_Flex"})
table.insert(TauntGUI.Taunts,{"Flex_02","f_Flex_02"})
table.insert(TauntGUI.Taunts,{"FlippnSexy","f_FlippnSexy"})
table.insert(TauntGUI.Taunts,{"Floppy_Dance","f_Floppy_Dance"})
table.insert(TauntGUI.Taunts,{"FlossDance","f_FlossDance"})
table.insert(TauntGUI.Taunts,{"Fonzie_Pistol","f_Fonzie_Pistol"})
table.insert(TauntGUI.Taunts,{"Fresh","f_Fresh"})
table.insert(TauntGUI.Taunts,{"FrisbeeShow","f_FrisbeeShow"})
table.insert(TauntGUI.Taunts,{"Funk_Time","f_Funk_Time"})
table.insert(TauntGUI.Taunts,{"Gabby_HipHop","f_Gabby_HipHop"})
table.insert(TauntGUI.Taunts,{"GlowStickDance","f_GlowStickDance"})
table.insert(TauntGUI.Taunts,{"GoatDance","f_GoatDance"})
table.insert(TauntGUI.Taunts,{"GolfClap","f_GolfClap"})
table.insert(TauntGUI.Taunts,{"Golfer_Clap","f_Golfer_Clap"})
table.insert(TauntGUI.Taunts,{"GothDance","f_GothDance"})
table.insert(TauntGUI.Taunts,{"GrooveJam","f_GrooveJam"})
table.insert(TauntGUI.Taunts,{"Grooving","f_Grooving"})
table.insert(TauntGUI.Taunts,{"Guitar_Walk","f_Guitar_Walk"})
table.insert(TauntGUI.Taunts,{"GunSpinnerTeacup","f_GunSpinnerTeacup"})
table.insert(TauntGUI.Taunts,{"Halloween_Candy","f_Halloween_Candy"})
table.insert(TauntGUI.Taunts,{"HandSignals","f_HandSignals"})
table.insert(TauntGUI.Taunts,{"HandstandLeg_Dab","f_HandstandLeg_Dab"})
table.insert(TauntGUI.Taunts,{"HappySkipping","f_HappySkipping"})
table.insert(TauntGUI.Taunts,{"Happy_Wave","f_Happy_Wave"})
table.insert(TauntGUI.Taunts,{"Headbanger","f_Headbanger"})
table.insert(TauntGUI.Taunts,{"Head_Bounce","f_Head_Bounce"})
table.insert(TauntGUI.Taunts,{"Heelclick","f_Heelclick"})
table.insert(TauntGUI.Taunts,{"HillBilly_Shuffle","f_HillBilly_Shuffle"})
table.insert(TauntGUI.Taunts,{"HiLoWave","f_HiLoWave"})
table.insert(TauntGUI.Taunts,{"HipHop_01","f_HipHop_01"})
table.insert(TauntGUI.Taunts,{"HipToBeSquare","f_HipToBeSquare"})
table.insert(TauntGUI.Taunts,{"Hip_Hop","f_Hip_Hop"})
table.insert(TauntGUI.Taunts,{"Hip_Hop_Gestures_1","f_Hip_Hop_Gestures_1"})
table.insert(TauntGUI.Taunts,{"Hip_Hop_S7","f_Hip_Hop_S7"})
table.insert(TauntGUI.Taunts,{"Hitchhiker","f_Hitchhiker"})
table.insert(TauntGUI.Taunts,{"Hit_The_Woah","f_Hit_The_Woah"})
table.insert(TauntGUI.Taunts,{"Hi_Five_Slap","f_Hi_Five_Slap"})
table.insert(TauntGUI.Taunts,{"HoldOnAMinute","f_HoldOnAMinute"})
table.insert(TauntGUI.Taunts,{"Hooked","f_Hooked"})
table.insert(TauntGUI.Taunts,{"Hopper","f_Hopper"})
table.insert(TauntGUI.Taunts,{"Hotstuff","f_Hotstuff"})
table.insert(TauntGUI.Taunts,{"Hula","f_Hula"})
table.insert(TauntGUI.Taunts,{"HulaHoop","f_HulaHoop"})
table.insert(TauntGUI.Taunts,{"HulaHoopChallenge","f_HulaHoopChallenge"})
table.insert(TauntGUI.Taunts,{"IceKing","f_IceKing"})
table.insert(TauntGUI.Taunts,{"IDontKnow","f_IDontKnow"})
table.insert(TauntGUI.Taunts,{"IHeartYou","f_IHeartYou"})
table.insert(TauntGUI.Taunts,{"IndiaDance","f_IndiaDance"})
table.insert(TauntGUI.Taunts,{"InfiniDab","f_InfiniDab"})
table.insert(TauntGUI.Taunts,{"Intensity","f_Intensity"})
table.insert(TauntGUI.Taunts,{"IrishJig","f_IrishJig"})
table.insert(TauntGUI.Taunts,{"I_Break_You","f_I_Break_You"})
table.insert(TauntGUI.Taunts,{"Jammin","f_Jammin"})
table.insert(TauntGUI.Taunts,{"Jaywalk","f_Jaywalk"})
table.insert(TauntGUI.Taunts,{"Jazz_Dance","f_Jazz_Dance"})
table.insert(TauntGUI.Taunts,{"Jazz_Hands","f_Jazz_Hands"})
table.insert(TauntGUI.Taunts,{"Juggler","f_Juggler"})
table.insert(TauntGUI.Taunts,{"JumpingJack","f_JumpingJack"})
table.insert(TauntGUI.Taunts,{"Kitty_Cat","f_Kitty_Cat"})
table.insert(TauntGUI.Taunts,{"KoreanEagle","f_KoreanEagle"})
table.insert(TauntGUI.Taunts,{"Kpop_02","f_Kpop_02"})
table.insert(TauntGUI.Taunts,{"Kpop_03","f_Kpop_03"})
table.insert(TauntGUI.Taunts,{"Kpop_04","f_Kpop_04"})
table.insert(TauntGUI.Taunts,{"KPop_Dance03","f_KPop_Dance03"})
table.insert(TauntGUI.Taunts,{"KungFu_Salute","f_KungFu_Salute"})
table.insert(TauntGUI.Taunts,{"KungFu_Shadowboxing","f_KungFu_Shadowboxing"})
table.insert(TauntGUI.Taunts,{"Laugh","f_Laugh"})
table.insert(TauntGUI.Taunts,{"LazerDance","f_LazerDance"})
table.insert(TauntGUI.Taunts,{"LazerFlex","f_LazerFlex"})
table.insert(TauntGUI.Taunts,{"Lazy_Shuffle","f_Lazy_Shuffle"})
table.insert(TauntGUI.Taunts,{"LivingLarge","f_LivingLarge"})
table.insert(TauntGUI.Taunts,{"Llama","f_Llama"})
table.insert(TauntGUI.Taunts,{"LlamaMarch","f_LlamaMarch"})
table.insert(TauntGUI.Taunts,{"Look_At_This","f_Look_At_This"})
table.insert(TauntGUI.Taunts,{"Loser_Dance","f_Loser_Dance"})
table.insert(TauntGUI.Taunts,{"Luchador","f_Luchador"})
table.insert(TauntGUI.Taunts,{"Make_It_Rain_V2","f_Make_It_Rain_V2"})
table.insert(TauntGUI.Taunts,{"Maracas","f_Maracas"})
table.insert(TauntGUI.Taunts,{"Marat","f_Marat"})
table.insert(TauntGUI.Taunts,{"MartialArts","f_MartialArts"})
table.insert(TauntGUI.Taunts,{"Mask_Off","f_Mask_Off"})
table.insert(TauntGUI.Taunts,{"Mello","f_Mello"})
table.insert(TauntGUI.Taunts,{"Mic_Drop","f_Mic_Drop"})
table.insert(TauntGUI.Taunts,{"Mime","f_Mime"})
table.insert(TauntGUI.Taunts,{"Mind_Blown","f_Mind_Blown"})
table.insert(TauntGUI.Taunts,{"Moonwalking","f_Moonwalking"})
table.insert(TauntGUI.Taunts,{"MyIdol","f_MyIdol"})
table.insert(TauntGUI.Taunts,{"NeedToPee","f_NeedToPee"})
table.insert(TauntGUI.Taunts,{"Octopus","f_Octopus"})
table.insert(TauntGUI.Taunts,{"OG_RunningMan","f_OG_RunningMan"})
table.insert(TauntGUI.Taunts,{"OneArmFloss","f_OneArmFloss"})
table.insert(TauntGUI.Taunts,{"Peely_Blender","f_Peely_Blender"})
table.insert(TauntGUI.Taunts,{"PinWheelSpin","f_PinWheelSpin"})
table.insert(TauntGUI.Taunts,{"Pirate_Gold","f_Pirate_Gold"})
table.insert(TauntGUI.Taunts,{"PizzaTime","f_PizzaTime"})
table.insert(TauntGUI.Taunts,{"PogoTraversal","PogoTraversal"})
table.insert(TauntGUI.Taunts,{"PopLock","f_PopLock"})
table.insert(TauntGUI.Taunts,{"PraiseTheTomato","f_PraiseTheTomato"})
table.insert(TauntGUI.Taunts,{"Present_Opening","f_Present_Opening"})
table.insert(TauntGUI.Taunts,{"ProtestAlien","f_ProtestAlien"})
table.insert(TauntGUI.Taunts,{"PumpkinDance","f_PumpkinDance"})
table.insert(TauntGUI.Taunts,{"Pump_Dance","f_Pump_Dance"})
table.insert(TauntGUI.Taunts,{"RageQuit","f_RageQuit"})
table.insert(TauntGUI.Taunts,{"RedCard","f_RedCard"})
table.insert(TauntGUI.Taunts,{"Regal_Wave","f_Regal_Wave"})
table.insert(TauntGUI.Taunts,{"RespectThePeace","f_RespectThePeace"})
table.insert(TauntGUI.Taunts,{"RideThePony","f_RideThePony"})
table.insert(TauntGUI.Taunts,{"RideThePony_v2","f_RideThePony_v2"})
table.insert(TauntGUI.Taunts,{"RobotDance","f_RobotDance"})
table.insert(TauntGUI.Taunts,{"Rocket_Rodeo","f_Rocket_Rodeo"})
table.insert(TauntGUI.Taunts,{"RockPaperScissor_Rock","f_RockPaperScissor_Rock"})
table.insert(TauntGUI.Taunts,{"Rock_Guitar","f_Rock_Guitar"})
table.insert(TauntGUI.Taunts,{"Rooster_Mech","f_Rooster_Mech"})
table.insert(TauntGUI.Taunts,{"Running","f_Running"})
table.insert(TauntGUI.Taunts,{"Runningv3","f_Runningv3"})
table.insert(TauntGUI.Taunts,{"Sad_Trombone","f_Sad_Trombone"})
table.insert(TauntGUI.Taunts,{"Salt","f_Salt"})
table.insert(TauntGUI.Taunts,{"Salute","f_Salute"})
table.insert(TauntGUI.Taunts,{"Scorecard","f_Scorecard"})
table.insert(TauntGUI.Taunts,{"Security_Guard","f_Security_Guard"})
table.insert(TauntGUI.Taunts,{"ShadowBoxer","f_ShadowBoxer"})
table.insert(TauntGUI.Taunts,{"Shaka","f_Shaka"})
table.insert(TauntGUI.Taunts,{"Shaolin","f_Shaolin"})
table.insert(TauntGUI.Taunts,{"Shinobi","f_Shinobi"})
table.insert(TauntGUI.Taunts,{"Showstopper_Dance","f_Showstopper_Dance"})
table.insert(TauntGUI.Taunts,{"SignSpinner","f_SignSpinner"})
table.insert(TauntGUI.Taunts,{"Sit_and_Spin","f_Sit_and_Spin"})
table.insert(TauntGUI.Taunts,{"SkeletonDance","f_SkeletonDance"})
table.insert(TauntGUI.Taunts,{"SmokeBombFail","f_SmokeBombFail"})
table.insert(TauntGUI.Taunts,{"Smooth_Ride","f_Smooth_Ride"})
table.insert(TauntGUI.Taunts,{"Snap","f_Snap"})
table.insert(TauntGUI.Taunts,{"Sneaky","f_Sneaky"})
table.insert(TauntGUI.Taunts,{"SoccerJuggling","f_SoccerJuggling"})
table.insert(TauntGUI.Taunts,{"SomethingStinks","f_SomethingStinks"})
table.insert(TauntGUI.Taunts,{"Sparkles","f_Sparkles"})
table.insert(TauntGUI.Taunts,{"SpeedRun","f_SpeedRun"})
table.insert(TauntGUI.Taunts,{"Spray","f_Spray"})
table.insert(TauntGUI.Taunts,{"Sprinkler","f_Sprinkler"})
table.insert(TauntGUI.Taunts,{"Spyglass","f_Spyglass"})
table.insert(TauntGUI.Taunts,{"StageBow","f_StageBow"})
table.insert(TauntGUI.Taunts,{"StatuePose","f_StatuePose"})
table.insert(TauntGUI.Taunts,{"Strawberry_Pilot","f_Strawberry_Pilot"})
table.insert(TauntGUI.Taunts,{"SuckerPunch","f_SuckerPunch"})
table.insert(TauntGUI.Taunts,{"Swim_Dance","f_Swim_Dance"})
table.insert(TauntGUI.Taunts,{"SwingDance","f_SwingDance"})
table.insert(TauntGUI.Taunts,{"Switch_Witch_Bad2Good","f_Switch_Witch_Bad2Good"})
table.insert(TauntGUI.Taunts,{"Switch_Witch_Good2Bad","f_Switch_Witch_Good2Bad"})
table.insert(TauntGUI.Taunts,{"TacoTime","f_TacoTime"})
table.insert(TauntGUI.Taunts,{"TaiChi","f_TaiChi"})
table.insert(TauntGUI.Taunts,{"Take_The_Elf","f_Take_The_Elf"})
table.insert(TauntGUI.Taunts,{"Take_the_W","f_Take_the_W"})
table.insert(TauntGUI.Taunts,{"TechnoZombie","f_TechnoZombie"})
table.insert(TauntGUI.Taunts,{"Texting","f_Texting"})
table.insert(TauntGUI.Taunts,{"TheQuickSweeper","f_TheQuickSweeper"})
table.insert(TauntGUI.Taunts,{"The_Alien","f_The_Alien"})
table.insert(TauntGUI.Taunts,{"ThighSlapper","f_ThighSlapper"})
table.insert(TauntGUI.Taunts,{"ThumbsDown","f_ThumbsDown"})
table.insert(TauntGUI.Taunts,{"ThumbsUp","f_ThumbsUp"})
table.insert(TauntGUI.Taunts,{"TimeOut","f_TimeOut"})
table.insert(TauntGUI.Taunts,{"TimetravelBackflip","f_TimetravelBackflip"})
table.insert(TauntGUI.Taunts,{"TomatoThrow","f_TomatoThrow"})
table.insert(TauntGUI.Taunts,{"Torch_Snuffer","f_Torch_Snuffer"})
table.insert(TauntGUI.Taunts,{"Toss","f_Toss"})
table.insert(TauntGUI.Taunts,{"Touchdown_Dance","f_Touchdown_Dance"})
table.insert(TauntGUI.Taunts,{"TPose","f_TPose"})
table.insert(TauntGUI.Taunts,{"TreadmillDance","f_TreadmillDance"})
table.insert(TauntGUI.Taunts,{"TRex","f_TRex"})
table.insert(TauntGUI.Taunts,{"Trophy_Celebration","f_Trophy_Celebration"})
table.insert(TauntGUI.Taunts,{"Twist","f_Twist"})
table.insert(TauntGUI.Taunts,{"UkuleleTime","f_UkuleleTime"})
table.insert(TauntGUI.Taunts,{"WackyInflatable","f_WackyInflatable"})
table.insert(TauntGUI.Taunts,{"WarehouseDance","f_WarehouseDance"})
table.insert(TauntGUI.Taunts,{"Wave2","f_Wave2"})
table.insert(TauntGUI.Taunts,{"Wave_Dance","f_Wave_Dance"})
table.insert(TauntGUI.Taunts,{"Wheres_Matt","f_Wheres_Matt"})
table.insert(TauntGUI.Taunts,{"Wiggle","f_Wiggle"})
table.insert(TauntGUI.Taunts,{"WindmillFloss","f_WindmillFloss"})
table.insert(TauntGUI.Taunts,{"Wizard","f_Wizard"})
table.insert(TauntGUI.Taunts,{"Wolf_Howl","f_Wolf_Howl"})
table.insert(TauntGUI.Taunts,{"Wrist_Flick","f_Wrist_Flick"})
table.insert(TauntGUI.Taunts,{"YayExcited","f_YayExcited"})
table.insert(TauntGUI.Taunts,{"Yeet","f_Yeet"})
table.insert(TauntGUI.Taunts,{"Youre_Awesome","f_Youre_Awesome"})
table.insert(TauntGUI.Taunts,{"You_Bore_Me","f_You_Bore_Me"})
table.insert(TauntGUI.Taunts,{"Zippy_Dance","f_Zippy_Dance"})
table.insert(TauntGUI.Taunts,{"ZombieWalk","f_ZombieWalk"})


function TauntGUI.OpenGUI()
    if IsValid(TauntGUI.Main) then
        TauntGUI.Main:Remove()
    end
    TauntGUI.Main = vgui.Create("DFrame")
    TauntGUI.Main:SetSize(ScrW() * 0.5, ScrH() * 0.5)
    TauntGUI.Main:Center()
    TauntGUI.Main:SetTitle("Taunt GUI")
    TauntGUI.Main:SetDraggable(false)
    TauntGUI.Main:ShowCloseButton(false)
    TauntGUI.Main:MakePopup()
    TauntGUI.Main.Paint = function(self, w, h)
        draw.RoundedBox(0, 0, 0, w, h, Color(0, 0, 0, 200))
    end
    local close = vgui.Create("DButton", TauntGUI.Main)
    close:SetSize(20, 20)
    close:SetPos(TauntGUI.Main:GetWide() - 20, 0)
    close:SetText("X")
    close.DoClick = function()
        TauntGUI.Main:Remove()
    end
    close.Paint = function(self, w, h)
        draw.RoundedBox(0, 0, 0, w, h, Color(255, 0, 0, 255))
    end
    local tauntlist = vgui.Create("DListView", TauntGUI.Main)
    tauntlist:Dock(LEFT)
    tauntlist:SetSize(TauntGUI.Main:GetWide() * 0.5, TauntGUI.Main:GetTall())
    tauntlist:AddColumn("Taunts")
    for k, v in pairs(TauntGUI.Taunts) do
        local line = tauntlist:AddLine(v[1])
        line.taunt = v[2]
    end
    local rightwrapper = vgui.Create("DPanel", TauntGUI.Main)
    rightwrapper:Dock(FILL)
    rightwrapper.Paint = function(self, w, h)
    end

    local preview  = vgui.Create("DModelPanel", rightwrapper)
    preview:Dock(FILL)
    preview:SetSize(TauntGUI.Main:GetWide() * 0.5, TauntGUI.Main:GetTall())
    preview:SetModel(LocalPlayer():GetModel())
    preview:SetAnimated(true)
    preview:SetCamPos(Vector(50, 50, 50))
    function preview:LayoutEntity( ent )
        ent:SetAngles(Angle(0, 45, 0))
        if ( self.bAnimated ) then
            self:RunAnimation()
        end
        if(ent:GetCycle() >= 0.99) then
            ent:SetCycle(0)
        end
        return
    end

    tauntlist.OnRowSelected = function(self, index, line)
        local taunt = line.taunt
        preview.Entity:ResetSequence(taunt)
        preview:RunAnimation()
        preview:SetAnimSpeed(1)
    end

    local buttons = vgui.Create("DPanel", rightwrapper)
    buttons:Dock(BOTTOM)
    buttons.Paint = function(self, w, h)
    end

    local play = vgui.Create("DButton", buttons)
    play:Dock(RIGHT)
    play:SetText("Play")

    play.DoClick = function()
        local line = tauntlist:GetSelectedLine()
        if(line == nil) then return end
        local taunt = tauntlist:GetLine(line).taunt
        RunConsoleCommand(taunt)
        TauntGUI.Main:Remove()
    end

    local setAsDefault = vgui.Create("DButton", buttons)
    setAsDefault:Dock(RIGHT)
    setAsDefault:SetText("Set as default")
    setAsDefault:SizeToContents()
    setAsDefault.DoClick = function()
        local line = tauntlist:GetSelectedLine()
        if(line == nil) then return end
        local taunt = tauntlist:GetLine(line).taunt
        RunConsoleCommand("cl_taunt", taunt)
        --TauntGUI.Main:Remove()
    end

end


concommand.Add("taunts", TauntGUI.OpenGUI)

concommand.Add("taunt", function(ply)
    RunConsoleCommand(ply:GetInfo("cl_taunt"))
end)